<a href="https://colab.research.google.com/github/svetlana030703/takeit/blob/main/%22%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Задание по практике 1

##Загрузка датасета
В файле classification datasets расположены ссылки на датасеты. Выберите один в соответствии со своим вариантом, скачайте и прочитайте файл

**Не забудьте загрузить нужные библиотеки**

Например: pip3 install pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("crimes_against_women_2001-2014.csv")
df

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0
...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0

##Первое знакомство с датасетом
В следующих ячейках выведите:


1.   Колонки датасета
2.   Первые 5 значений
3.   Последние 5 значений
4.   Статистику по числовым колонкам

In [ ]:
#Колонки
list(df.columns)

['Unnamed: 0',
 'STATE/UT',
 'DISTRICT',
 'Year',
 'Rape',
 'Kidnapping and Abduction',
 'Dowry Deaths',
 'Assault on women with intent to outrage her modesty',
 'Insult to modesty of Women',
 'Cruelty by Husband or his Relatives',
 'Importation of Girls']

In [ ]:
#Первые 5 значений
df.head(5)

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0

In [ ]:
#Последние 5 значений
df.tail(5)

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
10672,832,Lakshadweep,Lakshadweep,2014,1,0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014,1,0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014,3,1,0,12,1,1,0
10675,835,Puducherry,Puducherry,2014,7,6,1,20,7,3,0
10676,836,Puducherry,Total District(s),2014,10,7,1,32,8,4,0

In [ ]:
#Статистику
df.describe()

,Unnamed: 0,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
count,10677.000000,10677.000000,10677.000000,10677.000000,10677.000000,10677.000000,10677.000000,10677.000000,10677.000000
mean,3871.570198,2007.697949,57.989885,69.888358,20.181699,113.539196,27.419313,209.224314,0.175330
std,2816.369918,4.046874,214.230398,311.623450,98.276531,458.903951,167.806797,905.664362,2.228637
min,0.000000,2001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1009.000000,2004.000000,8.000000,6.000000,1.000000,10.000000,0.000000,11.000000,0.000000
50%,3678.000000,2008.000000,22.000000,20.000000,5.000000,34.000000,2.000000,50.000000,0.000000
75%,6347.000000,2011.000000,44.000000,49.000000,16.000000,85.000000,12.000000,144.000000,0.000000
max,9016.000000,2014.000000,5076.000000,10626.000000,2469.000000,10001.000000,4970.000000,23278.000000,83.000000

**Ответьте на следующие вопросы:**


1.   Какие средние значения в каждой числовой колонке вашего датасета?
2.   Минимальные и максимальные значения в каждой числовой колонке вашего датасета



1.   **Ответ 1.**
2.   **Ответ 2.**

In [ ]:
#среднее значение
df.mean(numeric_only=True)

Unnamed: 0                                             3871.570198
Year                                                   2007.697949
Rape                                                     57.989885
Kidnapping and Abduction                                 69.888358
Dowry Deaths                                             20.181699
Assault on women with intent to outrage her modesty     113.539196
Insult to modesty of Women                               27.419313
Cruelty by Husband or his Relatives                     209.224314
Importation of Girls                                      0.175330
dtype: float64

In [ ]:
#минимальное значение
df.min(numeric_only=True)

Unnamed: 0                                                0
Year                                                   2001
Rape                                                      0
Kidnapping and Abduction                                  0
Dowry Deaths                                              0
Assault on women with intent to outrage her modesty       0
Insult to modesty of Women                                0
Cruelty by Husband or his Relatives                       0
Importation of Girls                                      0
dtype: int64

In [ ]:
#максимальное значение
df.max(numeric_only=True)

Unnamed: 0                                              9016
Year                                                    2014
Rape                                                    5076
Kidnapping and Abduction                               10626
Dowry Deaths                                            2469
Assault on women with intent to outrage her modesty    10001
Insult to modesty of Women                              4970
Cruelty by Husband or his Relatives                    23278
Importation of Girls                                      83
dtype: int64

##Типизация
Присвойте соответствующим колонкам один из типов (category, float, int)

In [ ]:

df.Year = df.Year.astype("float")
df.DISTRICT = df.DISTRICT.astype("category")
df.Rape= df.Rape.astype("int")

df.dtypes
#Вывести типы колонок тут

Unnamed: 0                                                int64
STATE/UT                                                 object
DISTRICT                                               category
Year                                                    float64
Rape                                                      int64
Kidnapping and Abduction                                  int64
Dowry Deaths                                              int64
Assault on women with intent to outrage her modesty       int64
Insult to modesty of Women                                int64
Cruelty by Husband or his Relatives                       int64
Importation of Girls                                      int64
dtype: object

Какие признаки вы можете выделить в своем датасете (категориальные, числовые и др., **минимум 3 разных**, помните что можно также выделить признаки более точно, например числовые - порядковые, количественные и т.д.)?

Количественные(Dowry Deaths), Категориальная(Year), Порядковое(Unnamed)

##Фильтрация
Офильтруйте 3 колонки вашего датасета и выведите результат

In [ ]:
#Фильтр колонки 1
df[df["Year"] > 2013]

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
9840,0,Andhra Pradesh,Anantapur,2014.0,35,106,25,436,26,165,0
9841,1,Andhra Pradesh,Chittoor,2014.0,32,34,17,135,94,278,0
9842,2,Andhra Pradesh,Cuddapah,2014.0,28,16,16,215,12,91,0
9843,3,Andhra Pradesh,East Godavari,2014.0,85,25,7,519,62,464,0
9844,4,Andhra Pradesh,Guntakal Railway,2014.0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
10672,832,Lakshadweep,Lakshadweep,2014.0,1,0,0,1,2,0,0
10673,833,Lakshadweep,Total District(s),2014.0,1,0,0,1,2,0,0
10674,834,Puducherry,Karaikal,2014.0,3,1,0,12,1,1,0
10675,835,Puducherry,Puducherry,2014.0,7,6,1,20,7,3,0
10676,836,Puducherry,Total District(s),2014.0,10,7,1,32,8,4,0

In [ ]:
#Фильтр колонки 2

df[df["Rape"] > 23]

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001.0,50,30,16,149,34,175,0
2,2,ANDHRA PRADESH,CHITTOOR,2001.0,27,34,14,112,83,186,0
6,6,ANDHRA PRADESH,GUNTUR,2001.0,54,51,7,139,129,378,0
7,7,ANDHRA PRADESH,HYDERABAD CITY,2001.0,37,39,24,118,27,746,0
8,8,ANDHRA PRADESH,KARIMNAGAR,2001.0,56,49,62,414,81,224,0
...,...,...,...,...,...,...,...,...,...,...,...
10664,824,Delhi UT,South,2014.0,280,369,6,595,665,143,0
10665,825,Delhi UT,South-East,2014.0,266,402,24,469,123,312,0
10666,826,Delhi UT,South-West,2014.0,234,397,17,494,68,318,0
10670,830,Delhi UT,West,2014.0,251,546,13,484,63,416,0
10671,831,Delhi UT,Total District(s),2014.0,2096,4034,153,4322,1361,3173,0

In [ ]:
#Фильтр колонки 3
df[df["DISTRICT"] == "GUNTUR"]

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
6,6,ANDHRA PRADESH,GUNTUR,2001.0,54,51,7,139,129,378,0
722,722,ANDHRA PRADESH,GUNTUR,2002.0,46,71,13,186,85,434,0
1442,1442,ANDHRA PRADESH,GUNTUR,2003.0,46,77,22,228,99,399,0
2170,2170,ANDHRA PRADESH,GUNTUR,2004.0,46,60,32,186,104,397,0
2899,2899,ANDHRA PRADESH,GUNTUR,2005.0,55,56,16,166,203,366,0
3632,3632,ANDHRA PRADESH,GUNTUR,2006.0,47,35,15,281,236,427,0
4372,4372,ANDHRA PRADESH,GUNTUR,2007.0,43,79,28,292,214,569,0
5115,5115,ANDHRA PRADESH,GUNTUR,2008.0,48,65,26,306,99,496,0
5876,5876,ANDHRA PRADESH,GUNTUR,2009.0,40,62,26,340,451,720,0
6643,6643,ANDHRA PRADESH,GUNTUR,2010.0,38,39,20,282,409,456,0
7422,7422,ANDHRA PRADESH,GUNTUR,2011.0,40,57,8,223,140,494,0
8213,8213,ANDHRA PRADESH,GUNTUR,2012.0,23,53,21,252,83,656,0
9024,7,Andhra Pradesh,GUNTUR,2013.0,38,54,16,296,135,608,0

##Группировка
Сгруппируйте датасет по какому-либо категориальному признаку и выведите среднее значение численных колонок (см. метод mean в pandas)

In [ ]:
#Группировка
df.groupby(['DISTRICT']).mean(numeric_only=True)

,Unnamed: 0,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
DISTRICT,,,,,,,,,
24 PARGANAS NORTH,4426.000000,2007.0,153.692308,203.692308,55.230769,171.230769,4.230769,1474.000000,0.615385
24 PARGANAS SOUTH,4427.000000,2007.0,185.384615,193.615385,53.153846,126.923077,1.615385,1588.461538,0.230769
A and N ISLANDS,5080.000000,2007.0,3.000000,9.000000,1.000000,21.000000,2.000000,18.000000,0.000000
ADILABAD,3725.384615,2007.0,56.384615,47.461538,15.384615,152.461538,106.153846,353.076923,0.000000
AGAR,355.000000,2013.0,24.000000,8.000000,1.000000,41.000000,1.000000,30.000000,0.000000
...,...,...,...,...,...,...,...,...,...
Yamunanagar,213.000000,2014.0,50.000000,82.000000,7.000000,76.000000,0.000000,170.000000,0.000000
Yavatmal,450.000000,2014.0,108.000000,135.000000,12.000000,466.000000,504.000000,301.000000,0.000000
ZUNHEBOTO,4185.846154,2007.0,1.384615,0.461538,0.000000,0.000000,0.000000,0.000000,0.000000
ZZ TOTAL,483.228571,2013.0,963.057143,1482.314286,230.942857,2021.114286,359.685714,3396.171429,0.885714
Zunheboto,495.000000,2014.0,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

##Задание для гениев *
Агрегируйте числовой признак по категориальному признаку с использованием метода **без использования** библиотеки pandas, и вычислите медиану и среднее значение для каждой категории.

In [ ]:
#Агрегация